const Engine = {
    DEBUG_ENABLED: true,

    /* GameObject class */
    GOBJECT_DEFAULT_ANCHOR_X: 0.5,
    GOBJECT_DEFAULT_ANCHOR_Y: 0.5,
    GOBJECT_DEFAULT_WIDTH: 0,
    GOBJECT_DEFAULT_HEIGHT: 0,

    /* Sprite Class */
    SPRITE_LOADING_COLOR: '#d1bde1',
    SPRITE_SHOW_LOADING_ASSET: true,
    SPRITE_DEFAULT_ANCHOR_X: .5,
    SPRITE_DEFAULT_ANCHOR_Y: .5,
    SPRITE_ASSETLOADING_WIDTH:  100,
    SPRITE_ASSETLOADING_HEIGHT: 100 * 16/9
};